### ISSUE TITLE
Support for multiple tabs

### ISSUE THREAD

**Issue by kmafeni04** [pragtical/terminal#2]
Was wondering if there are any plans to support multiple tabs in the terminal, I usually don't need more than two and I've mostly supplemented it by using the console plugin as well but it would be nice to have a singular solution

**Comment by jgmdev** [comment]
You should be able to open different terminal tabs by executing the `terminal:open-tab` command

**Comment by kmafeni04** [comment]
> You should be able to open different terminal tabs by executing the `terminal:open-tab` command

OK, thank you

**Comment by kmafeni04** [comment]
Ok, thank you
